package com.igorhenss.SliceNdiceS.SliceNdiceS.enums;

public enum Subrole {

    HASTEE, BULLSEYE, RUNNY,
    CRYOUTER, ENRAGED,
    CLERIG, GEOMANCER, HYDROMANCER, NECROMANCER, PYROMANCER, UNIMANCER,
    DESERTER, GUARD, KINGSMAN, PALADIN

}
